### ISSUE TITLE
Module is_within is not found

### ISSUE THREAD

**Issue by pavelzach** [dwaithe/MaximaFinder#6]
I was able to install this module when downgrading to Python 3.11 (Python 3.12 does not work due to incompatibility in Cython).
However, I am receiving this error message:

```
Traceback (most recent call last):

  File "C:\My App\GUI.py", line 18, in <module>
    from findmaxima2d import find_maxima, find_local_maxima
  File "C:\My App\.venv\Lib\site-packages\findmaxima2d\__init__.py", line 1, in <module>
    from .findmaxima2d import find_local_maxima, find_maxima
  File "C:\My App\.venv\Lib\site-packages\findmaxima2d\findmaxima2d.py", line 3, in <module>
    from .cfindmaxima2d import find_maxima as cfind_maxima
  File "findmaxima2d\\cfindmaxima2d.pyx", line 7, in init findmaxima2d.cfindmaxima2d
ModuleNotFoundError: No module named 'is_within'
```

Both files that need to be compiled with Cython are present in the findmaxima2d folder with the .c extension.

**Comment by emre888** [comment]
despite I made this modificiation I still get this  'No module named 'is_within'' error.
